
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///vueblog?characterEncoding=utf8
    username: root
    password: 123456

#mybatis-plus扫描目录
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#服务器配置
server:
  port: 8081
  servlet:
    context-path: /blog


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认7天 单位秒）
  expire: 604800

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379