# spring 配置
#spring:
#  profiles:
#    active: dev

# web配置
server:
  servlet:
    context-path: /
  port: 8081


person:
  lastName: hello哈哈
  age: 18
  boss: false
  birth: 2021/7/12
  maps: { k1: v1,k2: 12 }
  lists:
    ‐ lisi
    ‐ zhaoliu
  dog:
    name: 小狗
    age: 16

logging:
  level:
    cn:
      edu:
        zzu: trace
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){blue}   %clr(${LOG_LEVEL_PATTERN:-%5p})   %clr(${PID:- }){magenta}   %clr(---){faint}   %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}   %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  file:
    name: d:/logs/TestSpringboot.log
    # path: d:/   # spring.log 默认名称
    max-size: 5KB
